name: Tests

on:
  push:
    branches:
      - master
      - develop

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm clean-install

      - name: Run tests
        run: npm test
